[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = 8MLVwFtwmP8jGgi65JU1agNjg5wCxPKl+unD7BtS21Y=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE


# [CTS Permanent Access] admin
[Peer]
PublicKey = ucvx70f1uvS9tBbHatDJW4oOlQ72pTZf65TFEdZrtRs=
AllowedIPs = 10.13.13.113/32
