[Interface]
Address = 10.13.13.2
PrivateKey = 8AYZbdqCzo2hDHBYEnhFpUxExdjurbaLxuLro7oFeUo=
ListenPort = 51820
DNS = 10.13.13.1

[Peer]
PublicKey = IynqNGlfd9ddt0yJK+BqB1oiZKwpNOz3XvQgx3q3QlM=
PresharedKey = IESxnpCdo6NSSFcNmdfNHgKcTPNdtk8oNveEzVdUeSg=
Endpoint = cts.celtechserv.com:51820
AllowedIPs = 10.13.0.0/16, 172.16.0.0/12
